todolist/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.verifica_atividade, name="index"),
    path('cadastro', views.cadastro, name="cadastro")
]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

todolist/core/models.py
from django.db import models

class TaskModel(models.Model):
    nome_atividade = models.CharField('Atividade',max_length=50)
    data_atividade = models.DateField('Data da Atividade')
    modificado_em = models.DateTimeField(
        verbose_name= 'Modificado em', 
        auto_now_add=False, auto_now=True)
    
    class Meta:
        verbose_name_plural = 'Atividades'
        verbose_name = 'Atividade'



    def __str__(self):
        return self.nome_atividade

todolist/core/forms.py
from .models import TaskModel
from django.forms import ModelForm

class TaskForm(ModelForm):
    class Meta:
        model = TaskModel
        fields = ['nome_atividade','data_atividade']
        error_messages = {
        'nome_atividade': {
            'required': ("Informe o nome da atividade."),
        },
        'data_atividade':{
            'required': ("Informe a data do atividade"),
        }
    }

    def clean_nome(self):
        nome_atividade = self.cleaned_data['nome_atividade']
        return nome_atividade.upper()
    
    def clean(self):
        self.cleaned_data = super().clean()
        return self.cleaned_data

todolist/core/views.py
from datetime import datetime
from django.shortcuts import redirect, render
from core.forms import TaskForm
from core.models import TaskModel


def cadastro(request):
    if request.method == 'POST':
        form_atividade = TaskForm(request.POST)
        if form_atividade.is_valid():
            TaskModel.objects.create(**form_atividade.cleaned_data)
            return redirect('/')
        else:
            contexto = {
                'form_atividade': form_atividade
            }
            return render (request, 'cadastro.html', contexto)
    else:
        contexto = {
            'form_atividade': TaskForm()
        }
        return render (request, 'cadastro.html', contexto)
    
def verifica_atividade(request): 
    data_atividade = datetime.now().date()
    qs = TaskModel.objects.all()
    verifica_data = qs.filter(
            data_atividade__year=data_atividade.year,
            data_atividade__month=data_atividade.month,
            data_atividade__day=data_atividade.day
    )
    nome_default = list()
    if len(verifica_data) > 0:
        for atividade in verifica_data:
            insercao = {
                "nome_atividade" : atividade.nome_atividade,
                "data_atividade": atividade.data_atividade,
            }
            nome_default.append(insercao)
        return render(request, 'index.html', {"nome_default": nome_default})
    return render(request, 'index.html', {"nome_default": [{"nome_atividade" : "Não há atividades para hoje."}]})    
    

todolist/core/templates/cadastro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
</head>
<body>
    <br><br>
    <form action={% url 'core:cadastro' %} novalidate method="POST">
        {% csrf_token %}
        <h3>Cadastro de Atividade | To-Do List</h3>
        Nome da Atividade: {{ form_atividade.nome_atividade }}
        <br>
        Insira a data:
        <input type="date" value= {{ form_atividade.data_atividade }}
        <br>
        <input type="submit" value="Cadastro">
    </form>
    <a href="/"><button>Home</button></a>
    
</body>
</html>

todolist/core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <br>   
    <h1>
        To-Do List:
    </h1> 
    <h2>
        {% for atividade in nome_default %}
        <center>
            {{ atividade.nome_atividade }}
        </center>
        {% endfor %}
    </h2>
    <br>
    <a href="/cadastro"><button>Cadastro</button></a>
    <br>
    <a href="/admin"><button>Edição</button></a>

</body>
</html>